In [523]:
import pandas as pd
import numpy as np

In [524]:
# Loading the dataset
cancer_data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data", header=None)

In [525]:
cancer_data.shape

(699, 11)

In [526]:
cancer_data.head()

0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

In [527]:
print(cancer_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       699 non-null    int64 
 1   1       699 non-null    int64 
 2   2       699 non-null    int64 
 3   3       699 non-null    int64 
 4   4       699 non-null    int64 
 5   5       699 non-null    int64 
 6   6       699 non-null    object
 7   7       699 non-null    int64 
 8   8       699 non-null    int64 
 9   9       699 non-null    int64 
 10  10      699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB
None


In [528]:
# Rows containing attributes with a '?'
cancer_data[cancer_data.isin(['?']).any(axis=1)]

0   1   2   3   4   5  6   7   8   9   10
23   1057013   8   4   5   1   2  ?   7   3   1   4
40   1096800   6   6   6   9   6  ?   7   8   1   2
139  1183246   1   1   1   1   1  ?   2   1   1   2
145  1184840   1   1   3   1   2  ?   2   1   1   2
158  1193683   1   1   2   1   3  ?   1   1   1   2
164  1197510   5   1   1   1   2  ?   3   1   1   2
235  1241232   3   1   4   1   2  ?   3   1   1   2
249   169356   3   1   1   1   2  ?   3   1   1   2
275   432809   3   1   3   1   2  ?   2   1   1   2
292   563649   8   8   8   1   2  ?   6  10   1   4
294   606140   1   1   1   1   2  ?   2   1   1   2
297    61634   5   4   3   1   2  ?   2   3   1   2
315   704168   4   6   5   6   7  ?   4   9   1   2
321   733639   3   1   1   1   2  ?   3   1   1   2
411  1238464   1   1   1   1   1  ?   2   1   1   2
617  1057067   1   1   1   1   1  ?   1   1   1   2

In [529]:
# Drop rows with missing attributes
cancer_data = cancer_data[(cancer_data[6] != "?")]

In [531]:
pd.isnull(cancer_data)

0      1      2      3      4      5      6      7      8      9   \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
694  False  False  False  False  False  False  False  False  False  False   
695  False  False  False  False  False  False  False  False  False  False   
696  False  False  False  False  False  False  False  False  False  False   
697  False  False  False  False  False  False  False  False  False  False   
698  False  False  False  False  False  False  False  False  False  False   

        10  
0    False  
1    False  
2    False  
3    False  
4    False  
..     ...  
694  False  
695  False  
696  False  
697  False  
698  False  

[683 rows x 11 columns]

In [532]:
# Retrieves the attributes with the exception of sample code number and target columns
X = cancer_data.values[:, 1:-1]
X = X.astype('int')

# Retrieves the 'target' column, which states whether cancer is benign or malignant
y = cancer_data.values[:, 10]
y = y.astype('int')
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [533]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [534]:
# define model
model = Sequential()
model.add(Dense(10, activation='relu', kernel_initializer='he_normal', input_shape=(9,)))
model.add(Dense(8, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(1, activation="sigmoid"))

In [535]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=["accuracy"])

In [536]:
# fit the model
model.fit(X_train, y_train, epochs=500, batch_size=32, verbose=0)

In [537]:
#predictions
y_pred = model.predict(X_test)
y_pred[:5]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [538]:
predictions = [2 if p>0.5 else 4 for p in y_pred]
predictions[:15]

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [539]:
y_test[:15]

array([4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4])

In [542]:
score = model.evaluate(X_test, y_test, verbose=1)
score

8/8 [==============================] - 0s 2ms/step - loss: -3311328.2500 - accuracy: 0.0000e+00


[-3311328.25, 0.0]

In [541]:
from sklearn.metrics import confusion_matrix, precision_score
confusion_matrix(y_test, predictions)
#precision_score(y_test, y_pred.round())

array([[142,   0],
       [ 84,   0]], dtype=int64)